---
title: "Bridging Psychology and AI"
description: |
  The Future of Human and Machine Personality
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Venue

Citadines Kurfürstendamm Berlin,  Olivaer Pl. 1, 10707 Berlin, Germany [website](https://www.discoverasr.com/en/citadines/germany/citadines-kurfurstendamm-berlin)

## Goals

The meeting will include input presentations and group discussions aimed at collaboratively developing perspectives on the two main questions:

1) How can AI advance personality psychology?
2) How can personality psychology inform evaluations of AI? 

The primary goal is to outline and plan an article that disseminates our insights to both the psychology and artificial intelligence communities. 

## Organization

Each session will begin with two presentations by two experts: the first presentation (~20min) introduces the theme of the session, whereas the second presentation (~10min) outlines open questions for us to discuss. Following these presentations, we will will split up into smaller groups to discuss the session's theme and open questions (~45min). Finally we will gather the insights from the group discussions in a plenary session moderated by the two initial presenters (~45min). 

## Schedule

### Tuesday, September 30  
**19:00** | Informal gathering & (unpaid) dinner  

### Wednesday, October 1  

**9:00 - 10:00** | **Introduction Round & Welcome**  
Welcome by the organizers. Participants introduce themselves (in 60 seconds or less). 

**10:00 - 12:00** | **Session 1 - What is personality in humans?**  
Introductory Presentation, followed by a commentary presentation, group discussions and a plenary discussion.

<ol>
<li style="margin-bottom: 2px;">*What are the core definitions, models, and assessments of personality?*</li>
<li style="margin-bottom: 2px;">*Can the scientific concept of personality be applied to non-human animals or machines?*</li>
<li style="margin-bottom: 2px;">*What are the current challenges concerning the scope and definition of personality?*</li>
</ol>

**12:00 - 13:00** | **Lunch Break**  

**13:00 - 15:00** | **Session 2 - Why can AI capture human personality?**  
Introductory Presentation, followed by a commentary presentation, group discussions and a plenary discussion.

<ol>
<li style="margin-bottom: 2px;">*What is AI, how does it work, and how can it be used to capture human personality?*</li>
<li style="margin-bottom: 2px;">*Which aspects (e.g., semantics vs. behavior) of personality can AI capture effectively and why?*</li>
<li style="margin-bottom: 2px;">*What theoretical challenges arise if an AI can accurately reproduce core findings from personality research?*</li>
</ol>

**15:00 - 15:30** | **Coffee Break**

**15:30 - 17:30** | **Session 3 - What is personality in AI?**<br>
Introductory Presentation, followed by a commentary presentation, group discussions and a plenary discussion.

<ol>
<li style="margin-bottom: 2px;">*How has personality been assessed in AI, and what has been found?*</li>
<li style="margin-bottom: 2px;">*How should we conceptualize personality in AI: as analogous to human personality or as a distinct concept?*</li>
<li style="margin-bottom: 2px;">*Do we need new personality tests for AI, and could they also help us understand humans?*</li>
</ol>


**19:00** | **Dinner**  

### Thursday, October 2  

**10:00 - 12:00** | **Session 4 - Changing personality in humans**  
Introductory Presentation, followed by a commentary presentation, group discussions and a plenary discussion.


<ol>
<li style="margin-bottom: 2px;">*When, how, and why does human personality change?*</li>
<li style="margin-bottom: 2px;">*How effectively can we induce momentary or stable personality changes in humans?*</li>
<li style="margin-bottom: 2px;">*What does the changeability of human personality imply for our conceptualization of personality?*</li>
</ol>


**12:00 - 13:00** | **Lunch Break**  

**13:00 - 15:00** | **Session 5 - Changing personality in AI**  
Introductory Presentation, followed by a commentary presentation, group discussions and a plenary discussion.

<ol>
<li style="margin-bottom: 2px;">*What techniques exist for changing personality in AI, and what are their potential applications?*</li>
<li style="margin-bottom: 2px;">*Does incidental (non-steered) change occur in an AI's personality?*</li>
<li style="margin-bottom: 2px;">*What does the changeability of AI personality imply for how we conceptualize it?*</li>
</ol>

**15:00 - 15:30** | **Coffee Break**

**15:30 - 16:30** | **Discussion: Conclusions & Future Steps**  
Summary of key takeaways, open questions and planning next actions.  

**16:30 - 17:30** | **Wrap-up & Farewell**  

**19:00** | **(unpaid) Dinner**  



